### ISSUE TITLE
About the reported results in Table 1 & 2

### ISSUE THREAD

**Issue by gangweix** [haesoochung/LAN-HDR#1]
Hi, greak work! In DeepHDRVideo (ICCV 21), the results on the Cinematic Video dataset and the DeepHDRVideo dataset are 40.34 and 45.46(dynamic set), but in you paper, the results are inconsistent. What are the different settings?

**Comment by haesoochung** [comment]
Hi! DeepHDRvideo (ICCV 21) used 21 videos from Cinematic Wide Gamut HDR-video and LiU HDRv Repository as well as Vimeo-90K dataset for training. But we only used the Vimeo-90K dataset, as mentioned in our paper.

**Comment by gangweix** [comment]
Ok, I see. But if using 21 videos from Cinematic Wide Gamut HDR-video and LiU HDRv for training can yield better results, why didn't this paper use it?

**Comment by haesoochung** [comment]
In our experiments, adding 21 videos did not bring significant improvement, while requiring far longer training time.

**Comment by gangweix** [comment]
Thank you for your reply！
